name: Publish
on:
  release:
    types: [released, prereleased]
jobs:
  build-native:
    name: Build native artifacts
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linuxX64
          - os: windows-latest
            target: mingwX64
#          - os: macos-latest
#            target: macosX64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib libx11-dev libxrandr-dev libgl1-mesa-dev libxcursor-dev libxi-dev wayland-protocols libwayland-dev libxkbcommon-dev libegl1-mesa-dev
      - name: Build for ${{ matrix.target }}
        run: ./gradlew :kgfw:compileKotlin${{ matrix.target }} --no-daemon --no-parallel --no-configuration-cache
        shell: bash
        timeout-minutes: 20
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: kgfw-${{ matrix.target }}
          path: kgfw/build/classes/kotlin/${{ matrix.target }}/main/**
          retention-days: 1

  publish:
    name: Publish to Maven Central
    needs: build-native
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib libx11-dev libxrandr-dev libgl1-mesa-dev libxcursor-dev libxi-dev wayland-protocols libwayland-dev libxkbcommon-dev libegl1-mesa-dev

      - name: Publish to MavenCentral
        run: ./gradlew publishToMavenCentral --no-configuration-cache --no-daemon
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
